# Generated by Django 2.0.4 on 2018-05-04 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180504_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='uploaded_at',
        ),
    ]
