# Generated by Django 2.0.4 on 2018-04-24 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_auto_20180424_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=70)),
                ('first', models.CharField(max_length=25)),
                ('last', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=10)),
                ('ord_list', models.ManyToManyField(to='shop.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
